services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.14
    container_name: etcd
    command:
      - /usr/local/bin/etcd
      - --name=etcd0
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd:2380
      - --initial-cluster=etcd0=http://etcd:2380
      - --initial-cluster-state=new
      - --listen-metrics-urls=http://0.0.0.0:2381
      - --log-level=info
    ports:
      - "2379:2379"
      - "2380:2380"
      - "2381:2381"
    volumes:
      - ./data:/etcd-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "etcdctl", "--endpoints=http://localhost:2379", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
  etcd-exporter:
    image: quay.io/brancz/etcd-exporter:v0.10.0
    container_name: etcd-exporter
    command:
      - --web.listen-address=:9106
      - --etcd.server=http://etcd:2379
    ports:
      - "9106:9106"
    depends_on:
      etcd:
        condition: service_healthy
    restart: unless-stopped
